fix broken custom attribute property serialization in `getECClassMetaData`
iTwin/imodel-native pull request #105
Opened 2023-01-11 21:57 UTC by MichaelBelousov

the baseaccess string argument to `JsonECInstanceWriter::WritePrimitiveValue` was being erroneously used always, when it's only meant for structs. This meant properties were being accessed like `PropName.PropName`, when they should have just been `PropName`, so nothing was written to the JSON.

2023-01-11 22:03 UTC, pmconne commented on iModelJsNodeAddon/api_package/ts/src/test/DgnDb.test.ts
> +  it.only("testGetECClassMetaData custom attributes", async () => {
Remove `.only`

2023-01-11 22:05 UTC, pmconne requested changes
Looks right to me but @khanaffan please review.

2023-01-11 22:19 UTC, MichaelBelousov commented on iModelJsNodeAddon/api_package/ts/src/test/DgnDb.test.ts
> +  it.only("testGetECClassMetaData custom attributes", async () => {
That's a face palm. Will do

2023-01-12 02:29 UTC, MichaelBelousov commented
I just started running backend js tests and am running into a number of issues. already hit both a hang and a separate abort on iModel close, but I don't know if it's related to my small change. I will revive this issue after I have confirmed whether those occur on master and submitted issues to the backlog for them if so

2023-01-12 16:09 UTC, MichaelBelousov commented
I still have issues with WAL mode (https://github.com/iTwin/itwinjs-backlog/issues/607), but rebasing this change on the pre-wal mode commit (with a cherry-pick to fix a crash), I pass the same tests as without these changes. That is, I fail all the geographical projection related tests and the objectvault test.
I don't believe this change has anything to do with any of that so I'm reopening

2023-01-12 16:10 UTC, MichaelBelousov commented on iModelJsNodeAddon/api_package/ts/src/test/DgnDb.test.ts
> +  it.only("testGetECClassMetaData custom attributes", async () => {
done

2023-01-12 17:05 UTC, khanaffan approved these changes

2023-01-12 18:27 UTC, pmconne approved these changes

2023-01-12 19:38 UTC, merged