Presentation: `CompareDateTime` floating point precision fix
iTwin/imodel-native pull request #123
Opened 2023-01-20 13:40 UTC by MartynasStrazdas

Closes https://github.com/iTwin/itwinjs-backlog/issues/574

2023-01-20 13:52 UTC, saskliutas requested changes

2023-01-20 13:52 UTC, saskliutas commented on iModelCore/ECPresentation/Source/Shared/ECExpressions/ECExpressionContextsProvider.cpp
> +            }
I think this can be extracted into separate function

2023-01-20 15:07 UTC, saskliutas commented on iModelCore/ECPresentation/Source/Shared/ECExpressions/ECExpressionContextsProvider.cpp
> +        Append(node.ToString());
```suggestion
        if (TryHandleCompareDateTimeEquality(node))
            return;
        Append(node.ToString());
        Utf8String left = node.GetLeftCP()->ToExpressionString();
```

2023-01-20 15:07 UTC, saskliutas commented on iModelCore/ECPresentation/Source/Shared/ECExpressions/ECExpressionContextsProvider.cpp
> +        if (left.StartsWith("CompareDateTimes") && right.StartsWith("0"))
How this will work with `0.5`?

2023-01-23 05:46 UTC, grigasp requested changes
Will this handle non-equality operators?
- `CompareDateTimes(this.PropertyName, 2) < 0`
- `CompareDateTimes(this.PropertyName, 2) <= 0`
- `CompareDateTimes(this.PropertyName, 2) > 0`
- `CompareDateTimes(this.PropertyName, 2) >= 0`

2023-01-23 10:55 UTC, grigasp approved these changes

2023-01-23 12:30 UTC, saskliutas approved these changes

2023-01-23 12:30 UTC, merged