Add cloudcache comments
iTwin/imodel-native pull request #179
Opened 2023-02-27 21:07 UTC by DanRod1999

Issue: https://github.com/iTwin/itwinjs-backlog/issues/579

added comments to all Cloudcontainer functions to clarify a cloudcache needs to be connected in order to use them.

2023-02-27 21:11 UTC, nick4598 commented on iModelCore/BeSQLite/CloudSqlite.cpp
> + * @note this function requires the cloudcache to be connected to the cloud container
Sorry I mentioned everything that includes a cloudcache, but this one actually instantiates the cloudcache

2023-02-27 21:11 UTC, DanRod1999 commented
Don't know if there is a better way to add these comments, but I noticed the `@note` tag was used in other places. If that isn't the proper use case I can change it.

2023-02-27 21:12 UTC, nick4598 commented on iModelCore/BeSQLite/CloudSqlite.cpp
> + * @note this function requires the cloudcache to be connected to the cloud container
Could we add to the message, "See CloudContainer::Connect"

2023-02-28 15:48 UTC, nick4598 commented
Just adding these comments in because iModelHub team ran into some trouble using some of the functions on CloudContainer not realizing they had to connect a cloudcache. People probably won't run into this again, but just incase.

2023-02-28 15:51 UTC, nick4598 approved these changes

2023-02-28 17:03 UTC, kabentley requested changes

2023-02-28 17:03 UTC, kabentley commented on iModelCore/BeSQLite/CloudSqlite.cpp
> + * @note This funciton does nothing if there is no cloudcache connected to the cloud container. See CloudContainer::Connect
this wording is backwards. You connect a CloudContainer to its CloudCache, not the other way around (multiple containers may connect to a single cache.)

2023-02-28 17:08 UTC, kabentley commented
Just to be clear, this whole api is internal. Using @note is fine, but only people looking at the code will see any of this. All the *real* documentation should be on the TypeScript layer. Please read that and see if it is clear about connect/disconnect. 

If the iModelHub team is using this outside of the TypeScript api, that can only be temporary from a fork.

2023-02-28 17:08 UTC, kabentley commented on iModelCore/BeSQLite/CloudSqlite.cpp
> + * @note This funciton does nothing if there is no cloudcache connected to the cloud container. See CloudContainer::Connect
also, "funciton"

2023-02-28 18:46 UTC, merged