Add support for BeDbUri
iTwin/imodel-native pull request #309
Opened 2023-06-07 13:16 UTC by khanaffan

2023-06-07 14:18 UTC, kabentley requested changes

2023-06-07 14:18 UTC, kabentley commented on iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
> +    Utf8String _canonicalPath;
use "m_" for all member names

2023-06-08 05:23 UTC, khanaffan commented on iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
> +    Utf8String _canonicalPath;
Fixed.

2023-06-08 05:27 UTC, khanaffan commented on iModelCore/BeSQLite/BeSQLite.cpp
> +    std::string s_output;
Fixed

2023-06-08 05:28 UTC, khanaffan commented on iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
> +    BeDbUri* m_uri; // forward declaration
`BeDbUri` uses `enums` from `Db:*` e.g. `Db::OpenMode` so we cannot declare `BeDbUri` before `Db` and so I cannot declare a member variable. Compilare complaints about it. There are two solutions
1. Take those Enums out of Db.
2. Use string variable instead  `Utf8String m_uri` and do `Db::GetUri() const { return BeDbUri(m_uri;}`.

For now, I applied 2) solution.

2023-06-08 08:27 UTC, pmconne commented on iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
> +    BeDbUri* m_uri; // forward declaration
Isn't #1 more straightforward?
```
enum struct DbOpenMode { ... };
struct BeDbUri {
  BeDbUri& SetOpenMode(DbOpenMode v) { ... }
  ...
};
struct Db {
  BeDbUri m_uri;
  using OpenMode = DbOpenMode;
  ...
};
```

2023-08-03 13:46 UTC, closed without merging