Fix cross join
iTwin/imodel-native pull request #419
Opened 2023-08-18 10:08 UTC by simasjar

closes iTwin/itwinjs-backlog#818

2023-08-18 15:38 UTC, khanaffan requested changes
Can you update CHANGES.md and add what new stuff you added and increment ECSQL version?

2023-08-21 05:48 UTC, simasjar commented
> Can you update CHANGES.md and add what new stuff you added and increment ECSQL version?
> 
> The next version for ECSQL will be `1.2.3.0` -> `1.2.4.0`

Updated

2023-08-21 08:41 UTC, rschili approved these changes

2023-08-22 13:29 UTC, khanaffan approved these changes

2023-08-22 13:35 UTC, merged