Enable SQLite ICU feature
iTwin/imodel-native pull request #722
Opened 2024-04-16 17:07 UTC by khanaffan

This PR enables ICU support in SQLite. It does not change the default NOCASE collation.

PR changes will be used to analyze existing iModels to see if they have Latin1 case folding issues in iQacs.

2024-04-16 19:23 UTC, nick4598 approved these changes

2024-04-16 19:38 UTC, aruniverse requested changes
isnt this breaking/write incompatible because it changes the index generated?

2024-04-16 19:44 UTC, khanaffan commented
> Isn't this breaking/write incompatible because it changes the index generated?

No, as the comment in PR says it does not change any default behavior. We are merging this so iQacs can find out stats about how many iModels in PROD has this issue. It will help us plan how we proceed/release it for all. Though i think the minimum prerequisite will be CodeService. That service has to have this feature on and at some point when everyone uses that service we can enable it by default.

2024-04-24 14:21 UTC, ColinKerr approved these changes

2024-04-24 14:29 UTC, aruniverse approved these changes

2024-04-24 14:49 UTC, pmconne commented on .vscode/launch.json
> +                "--gtest_filter=BeSQLiteDbTests.UnicodeSupport"
```suggestion
                "--gtest_filter=BeSQLiteDbTests.MaxBlobSize"
```
Revert.

2024-04-24 14:53 UTC, pmconne commented on iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
> +    DbResult SetNoCaseCollation(NoCaseCollation col) const;
Why is this function `const`?

2024-04-24 14:54 UTC, pmconne commented on iModelCore/BeSQLite/Tests/NonPublished/BeSQLiteDb_Test.cpp
> +#if 0 // Require ICU
Do you have some plan to enable this test? Does it fail to compile?

2024-04-24 16:29 UTC, khanaffan commented on iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
> +    DbResult SetNoCaseCollation(NoCaseCollation col) const;
Fixed.

2024-04-24 16:34 UTC, pmconne commented on iModelCore/BeSQLite/PublicAPI/BeSQLite/BeSQLite.h
> +    mutable NoCaseCollation m_noCaseCollation;
```suggestion
    NoCaseCollation m_noCaseCollation;
```
Now that `SetNoCaseCollation` is no longer `const`.

2024-04-24 20:10 UTC, khanaffan commented
@tcobbs-bentley do you have any idea why Android build keep failing with following error for me? 

```
* What went wrong:
Could not determine the dependencies of task ':app:packageDebug'.
> Could not create task ':app:mergeDebugAssets'.
   > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

2024-04-24 20:59 UTC, tcobbs-bentley commented
> @tcobbs-bentley do you have any idea why Android build keep failing with following error for me?
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':app:packageDebug'.
> > Could not create task ':app:mergeDebugAssets'.
>    > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
> ```

It's failing because after I updated the CI build setup yesterday to use a newer Android SDK to prevent build failures on a new build machine, things are failing. I have been doing everything I can to fix the problems, but every time I fix one problem a new one shows up. My latest fixes are currently running in two linked PRS:

https://github.com/iTwin/imodel-native/pull/738
https://github.com/iTwin/imodel-native-internal/pull/487

2024-04-25 09:49 UTC, rschili approved these changes

2024-04-25 16:39 UTC, tcobbs-bentley commented
/azp run imodel-native

2024-04-25 16:40 UTC, tcobbs-bentley commented
The PRs to fix the Android build problem have now merged, and I triggered another pipeline run here. Hopefully the pipeline will complete successfully now.

2024-04-29 13:31 UTC, merged