Version compare change summary performance improvements
iTwin/imodel-native pull request #781
Opened 2024-06-11 13:30 UTC by diegopinate

Changes to fix service case regarding high memory usage for 400 MB changeset. Summary of changes:

1. Allow skipping bounding box calculation and loading elements altogether.
2. Filter out relationship instances as those are handled by path traversal.
3. Simplify passing options.

Bounding box calculation for changed models was never used in version compare. The original reasoning behind it was to improve performance of viewed iModels by leveraging the volumes that contain changes and limit the tiles downloaded. However, as this feature was never leveraged by the frontend, and is just a waste of computation, allow it to be turned off via an option.

Relationships are also not necessary to be processed as part of the initial instance processing, so lower amount of cached data by simply skipping them. The

2024-06-11 21:39 UTC, pmconne requested changes
You updated itwinjs-core tests to always pass true for the new option but didn't add any tests to verify what happens when you pass false.

2024-06-14 16:00 UTC, diegopinate commented
> You updated itwinjs-core tests to always pass true for the new option but didn't add any tests to verify what happens when you pass false.

Good catch, thanks @pmconne, I added a new test to itwinjs-core that test both variations of wantBoundingBoxes

2024-06-14 17:07 UTC, pmconne approved these changes

2024-06-17 19:02 UTC, merged

2024-06-20 19:54 UTC, diegopinate commented
@mergiyio backport release/4.x