ECSchema deserialization should not fail due to invalid PropertyCategory
iTwin/imodel-native pull request #827
Opened 2024-08-07 15:09 UTC by RohitPtnkr1996

Fixes https://github.com/iTwin/itwinjs-backlog/issues/955

2024-08-07 15:16 UTC, rschili approved these changes

2024-08-07 15:19 UTC, pmconne requested changes
Awaiting corresponding itwinjs-core PR, right?

2024-08-07 17:00 UTC, khanaffan approved these changes

2024-08-08 10:32 UTC, pmconne approved these changes

2024-08-08 11:09 UTC, merged