Update azure-pipelines yml for release/4.8.x
iTwin/imodel-native pull request #828
Opened 2024-08-07 15:38 UTC by MikeNBentley

2024-08-07 15:44 UTC, DanRod1999 approved these changes

2024-08-07 15:53 UTC, DanRod1999 requested changes
This should be targeting the release/4.8.x branch

2024-08-07 15:55 UTC, MikeNBentley commented
> This should be targeting the release/4.8.x branch

2024-08-07 18:25 UTC, chuckkir approved these changes

2024-08-08 15:00 UTC, DanRod1999 commented
/azp run imodel-native

2024-08-09 02:45 UTC, merged