fix out-of-bounds array deref caught by asan
iTwin/imodel-native pull request #95
Opened 2023-01-05 22:46 UTC by dassaf4

Enhance `CurveVector::GetAnyFrenetFrame` with line string logic that seeks an optimal frame among the points, preferring the first such frame if it is good enough.

This is a backport from PowerPlatform, as requested by @swwilson-bsi.

2023-01-05 22:56 UTC, MichaelBelousov approved these changes

2023-01-06 14:21 UTC, EarlinLutz requested changes
This code was probably ported from old-style pre-allocated arrays that were certain to have sufficient size.

I think xyz1.push_back (xyz1[0]) still has potential problems if the size and capacity are already equal -- xyz1[0] should be copied into a local DPoint3d before being pushed.  But I'll be delighted if push_back is smart enough to not deallocate the input-time memory block before copying to a newly allocated block.

2023-01-06 21:51 UTC, dassaf4 commented
> I think xyz1.push_back (xyz1[0]) still has potential problems if the size and capacity are already equal...

Great point! I changed the push_back to use a local copy of the point, and also added a test to confirm that the compiler appends a valid point on push_back realloc just in case, as I'm sure I've seen (and used!) the anti-pattern elsewhere.

2023-01-09 22:48 UTC, EarlinLutz approved these changes

2023-01-09 23:09 UTC, MichaelBelousov commented
latest changes still pass the reported repro

2023-01-10 01:48 UTC, merged